baseURL = "https://fireguides.netlify.app/"
title = "Fireguides"
   # keep whatever you’re using
languageCode = "en-us"
[params]
  custom_css = ["css/custom.css"]
[menu]

  [[menu.main]]
  name = "Home"
  url = "/"
  weight = 1

  [[menu.main]]
  name = "Guides"
  url = "/guides/"
  weight = 2

  [[menu.main]]
  name = "About"
  url = "/about/"
  weight = 3

  [[menu.main]]
  name = "Contact"
  url = "/contact/"
  weight = 4
