name = "mytheme"
license = "MIT"
licenselink = "https://opensource.org/licenses/MIT"
description = "A fully custom theme"
tags = ["custom", "fireguides", "minimal"]
min_version = "0.111.3"

[author]
  name = "Tyler Morey"
  homepage = "https://github.com/Firecat3232"
